version: '3'

services:
  postgres:
    image: postgres:16.0
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: banco
      POSTGRES_USER: gabriel
      POSTGRES_PASSWORD: 19
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: 
      - batata
  server:
    container_name: server_container
    build: ./server
    ports:
      - 1234:1234
    depends_on:
      postgres:
        condition: "service_started"
    networks: 
      - batata
  app:
    container_name: app_container
    build: .
    ports:
      - 3000:3000
    depends_on:
      server:
        condition: "service_started"
    volumes:
      - .:/usr/src/app
    networks: 
      - batata
volumes:
  postgres_data:
networks:
  batata: 
    driver: bridge